version: 2.1
working_directory: ~/server
orbs:
  node: circleci/node@3.0.0

jobs:
  node_server:
    docker:
      - image: node:current-alpine

    working_directory: ~/server
    
    steps:
      - checkout
      - run: npm install
      
  node_client:
    docker:
      - image: node:current-alpine

    working_directory: ~/client
    steps:
      - checkout
      - run: npm install
      - run: npm install grunt
      - run: npm install karma
      - run: grunt

workflows:
  node-tests:
    jobs:
      - node_server
      - node_client
