version: 2.1
working_directory: ~/server
orbs:
  node: circleci/node@3.0.0

jobs:
  node_server:
    steps:
      - checkout
      - run: cd server/ && npm install
  node_client:
    steps:
      - checkout
      - run: cd client/ && npm install

workflows:
  node-tests:
    jobs:
      - node_server
      - node_client
